### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by afish31**

### CODE REVIEW

**Comment by alexanderswerdlow** [comment]
Can you provide the source logo file used and the site used to generate the new favicons @afish31 ?

**Comment by afish31** [comment]
> Can you provide the source logo file used and the site used to generate the new favicons @afish31 ?

https://www.favicongenerator.com/

**Comment by afish31** [comment]
> > Can you provide the source logo file used and the site used to generate the new favicons @afish31 ?
> 
> https://www.favicongenerator.com/

when i downloaded it this also appeared, <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">

**Comment by afish31** [comment]
> Can you provide the source logo file used and the site used to generate the new favicons @afish31 ?

knights301logo

**Pull request merged**
